### ISSUE TITLE
ReferenceError: 'require' is undefined

### ISSUE THREAD

**Issue by krassina** [Daddoon/Blazor.Polyfill#66] opened 2021-05-28 06:21 UTC
Getting this error on several of my blazor apps in IE when I add polyfill.

`Microsoft.JSInterop.JSException: 'require' is undefined
ReferenceError: 'require' is undefined
   at Anonymous function (https://localhost:44397/_framework/blazor.server.js:1:70657)
   at Anonymous function (https://localhost:44397/_framework/blazor.polyfill.min.js:1:87998)
   at n (https://localhost:44397/_framework/blazor.polyfill.min.js:1:91125)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Syncfusion.Blazor.Internal.SfBaseUtils.ImportModule(IJSRuntime jsRuntime, SfScriptModules scriptModule, String hashKey)
   at Syncfusion.Blazor.SfBaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Syncfusion.Blazor.Inputs.Internal.SfInputBase.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'QoJeYvM-oc9iEWSruAZKaaJWyvK7omA1p4Ze0CDQMSE'.`

**Comment by Daddoon** [comment] 2021-05-28 08:49
require and import are not supported on IE11.
You may try to mitigate this effect by bundling the library: https://github.com/Daddoon/Blazor.Polyfill#optional-javascript-isolation--module-import-support

However i don't know yet if your issue is a regression because of a blazor.server.js update or if it's one of your lib that is using require directly.

Can you try to launch a basic Blazor Server app, with the Blazor.Polyfill loaded in it , and test it on IE ? Does it start correctly ?

According to your stacktrace, i believe the issue may be related to the content that SyncFusion try to load:

```csharp
Syncfusion.Blazor.Internal.SfBaseUtils.ImportModule(IJSRuntime jsRuntime, SfScriptModules scriptModule, String hashKey)
```

If it's from this, typically, the workaround would be to add SyncFusion scripts to the Bundle intended for IE in order to avoid the require / import missing.

This cannot be workarounded directly by a polyfill at runtime, as require and import are ES6 languages features.

**Comment by krassina** [comment] 2021-05-28 10:29
Yes I tried it in a new project it worked until I added one Syncfusion component ill try the java isolation. Its just odd that the 18 version of Syncfusion all the components work without it

**Comment by Daddoon** [comment] 2021-05-28 11:28
What do you mean ? That previous versions of SyncFusion worked with the Polyfill without problem ?

It's maybe an internal change on their side, but without the control of what is called on their side, it may be difficult to workaround this issue in their library.

Ironically, SyncFusion is one of the few library that advertise my project in their documentation, [like here](https://blazor.syncfusion.com/documentation/common/how-to/render-blazor-server-app-in-ie/#how-to-render-the-blazor-server-application-in-ie-web-browser), but not sure that they test their library against it regularly.

According to their sample, even the library version reference seems outdated for my Polyfill.

You may try to reach their support directly, to see if they have any intention to patch or suggest a workaround for theses scenario in their lib.

**Comment by darrylluther** [comment] 2021-08-05 15:59
Were you ever able to resolve this? I'm facing the same issue and I'm also using the SyncFusion controls. I suspect SyncFusion will not modify their control library as IE 11 is not even officially supported for Blazor apps. I guess for now I will just use standard controls unless there is some other workaround.

**Comment by krassina** [comment] 2021-08-05 16:02
Nope just convinced my company to move to edge as default since it supports Syncfusion without polyfill.

**Comment by darrylluther** [comment] 2021-08-05 16:08
Gotcha, thanks for the reply. I have to support browsers outside our organization so I'm stuck supporting IE for now.

**Comment by krassina** [comment] 2021-08-05 16:16
If you are good at blazor components its not hard to mimic the things Syncfusion does without it. but Syncfusion is just easier since its all setup. it still has a javascript back end on their blazor version so if you do it all pure blazor it should be faster and cleaner code wise.

**Comment by Daddoon** [comment] 2021-11-15 00:56
Do you still have issue with SyncFusion ?

I have done some test with the SyncFusionSample project sandbox.
Did have to reorder some .js file in the _Host page and had to rebuild to ES5 dynamically at app boot in the wwwroot path (with some internal update i just made in order to test) and everything seemed to work on IE11.

I did not yet tested with the latest SyncFusion NuGet updates (still have to update them and test), but September build seems to work.

Also, just to clarify, current latest build of Blazor.Polyfill is targeted for Blazor / .NET 6.0.

**Comment by Daddoon** [comment] 2021-11-21 17:09
@darrylluther If you test this in the future (or if you have a repro project for this issue), you may try with the latest build to enable this option in your code in Startup.cs

```csharp
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            /* ... */

            //Add this call before app.UseStaticFiles
            app.UseBlazorPolyfill((options) =>
            {
                options.ES5ConversionScope = ES5ConversionScope.All; //Use All or RazorClassLibrary scope, depending the needs of your project. RazorClassLibrary is less "wide" and will only convert RCL library, the things that you can't fix by yourself manually easily. See the project doc for mor info !
                options.ForceES5Fallback = true; //Not mandatory but it will force to use and/or convert JS files when needed according to your ES5ConversionScope enum !
                options.JavascriptModuleImportEmulation = true;
                options.JavascriptModuleImportEmulationLibraryPath = "/es5module.min.js";
            });

            app.UseStaticFiles();
            /* ... */
        }
```

Keep me informed if you can.

**Comment by darrylluther** [comment] 2021-11-21 17:39
Will do. I'm tied up with some other projects at the moment, but it will
not be long before I will need to return to these projects that I'm trying
to get to run under IE with Syncfusion controls. Thanks for the information
and I'll report back on how it goes for me.

- Darryl

**Comment by Daddoon** [comment] 2021-12-04 18:37
I seem to have isolated the error about 'require' is undefined, as i encountered this issue while trying to use some SyncFusion controls.

Actually there was some 'errors' in transpilation by Babel. Not really an error but some code part was calling **require** but this kind of call is not available outside a Node environment.

However, next to theses calls, the things done are only string concatenations ( **require("".concat(n))** ) so theses faulty things has been corrected through a regex to only **"".concat(n)** .

An update is available here: https://www.nuget.org/packages/BlazorPolyfill.Server/6.0.100.3 .

Things should work now.

Closing...

**Closed by Daddoon** 2021-12-04 18:37 UTC
